/**
* The program calculates the money generated by solar cells on a sunny day. 
*
* 1. First the konown variables are declared 
* 2. Then the inputs are collected and parsed 
* 3. The calculation is made
* 4. The results are shown
*
* @author Olivia Fabreschi, olifab-1@student.ltu.se */
  import java.util.Scanner;
  import java.text.DateFormat;
  import java.text.ParseException;
  import java.text.SimpleDateFormat;
  import java.util.Date;
  import javax.swing.JOptionPane; 

  class Main {
  public static void main(String[] args) {
    
    //setup, variables and input variables
    Scanner input = new Scanner(System.in);
    Scanner userInput = new Scanner(System.in);
    // Set delimiter on one of the scanners to -
    userInput.useDelimiter("-");
    
    double electricityPrice = 0.9;
    double efficiency = 0.2;
    int solarRadiation = 166;
    double surface = 26.0 *1.7;
  
//screen print showing input and scanning input.  The time is entered in the form hh: mm.
    
  // prompt for input and read grade from user
  System.out.print("\nEnter today's date [mm-dd]>"); 
  String date = userInput.next();
  
  System.out.print("Enter time of sunrise [hh:mm]> "); 
  String sunrisestr = input.nextLine();
      
  System.out.print("Enter time of sunset [hh:mm]> "); 
  String sunsetstr = input.nextLine();
  
          
  //parse the inputs
  int dateint = Integer.parseInt(date);
  
  //calculate hours of sunlight
  SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
  Date d1 = sdf.parse(sunrisestr, new java.text.ParsePosition(0));
  Date d2 = sdf.parse(sunsetstr, new java.text.ParsePosition(0));

//calculate hours
    double diffMs = d2.getTime() - d1.getTime();
    double diffH = diffMs / (60.0 * 60.0 * 1000.0);
    double hour = diffH;

//error message if wrong
  if ((dateint < 06 || dateint > 07))
    {  
        System.out.println("Error in input. This program is only for June or July. Please restart and try again.");
        System.exit(0);
    }
      if (d1.after(d2))
    {  
        System.out.println("Error in input. Sunset time must be later than sunrise time. Please restart and try again.");
        System.exit(0);
    }
  
  
      
  //calculations - calculate what production takes place and finally what profit the sale of the entire production gives. Production (Wh) = Solar radiation (Wh / m2 / hour) x efficiency x surface (m2) x hours of sunshine

      double production = solarRadiation * efficiency * surface * hour /1000.0;

      //calculation of price
        double price = production * electricityPrice;
  
      //decimal reduction
      int noOfDecimals = 3;
      double scale = 0;
      scale = Math.pow(10, noOfDecimals); 


      double hourdec = 0;
      hourdec = Math.round(hour * scale) / scale;
    
      double productiondec = 0;
      productiondec = Math.round(production * scale) / scale;

      double pricedec = 0;
      pricedec = Math.round(price * scale) / scale;


  
      //print of results

       System.out.println("_________________________________");
      //System.out.println("Sun hours:");
      // System.out.println(hourdec);
      System.out.printf("\nSun hours is %.2f \n", hour);  
    
      //System.out.println("The production on x date is in kWh:");
     // System.out.println(productiondec);
      System.out.printf("The production is %.2f in kWh \n", productiondec);  
      //System.out.println("to a value of: SEK:");
     // System.out.println(pricedec);
         System.out.printf("To a value of: %.2f SEK:", pricedec );  

      
    }
  }